# Generated by Django 4.2.7 on 2024-03-06 20:41

from django.db import migrations, models
import django.db.models.deletion
import hope_hub.events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attribution", models.TextField(blank=True, verbose_name="Attribution")),
                ("statement", models.TextField(blank=True, verbose_name="Artist Statement")),
                ("alt_text", models.TextField(blank=True, verbose_name="Alt Text")),
                ("upload", models.FileField(upload_to=hope_hub.events.models.engagement_date_path)),
                ("engagement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="events.engagement")),
            ],
        ),
    ]
