# Generated by Django 4.2.7 on 2024-04-30 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_artifact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="engagement",
            options={"ordering": ("-date",)},
        ),
        migrations.AddField(
            model_name="engagement",
            name="created_by",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
