# Generated by Django 4.2.7 on 2024-05-02 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_engagement_options_engagement_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="engagement",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
