# Generated by Django 4.2.7 on 2024-05-02 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0004_engagement_created_engagement_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="alt_text",
            field=models.TextField(blank=True, verbose_name="Caption"),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="statement",
            field=models.TextField(blank=True, verbose_name="Connection to Heat Resilience"),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
