# Generated by Django 4.2.7 on 2024-05-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_artifact_alt_text_alter_artifact_statement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="place",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="events.place"
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="alt_text",
            field=models.TextField(blank=True, verbose_name="Image Caption"),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="attribution",
            field=models.TextField(blank=True, verbose_name="Attribution for Statement"),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="statement",
            field=models.TextField(blank=True, verbose_name="Connection to Community Resilience Statement"),
        ),
    ]
