# Generated by Django 4.2.7 on 2024-05-03 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_artifact_created_artifact_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="place",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="events.place"),
            preserve_default=False,
        ),
    ]
