# Generated by Django 4.2.7 on 2024-05-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_youtubelink_downloadablefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Caption for the image, also used as the alt text.",
                max_length=255,
                verbose_name="Image Caption",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="attribution",
            field=models.CharField(
                blank=True,
                help_text="Will appear as the attribution for the connection to resilience statement (aka who said the statement).",
                max_length=255,
                verbose_name="Attribution for Statement",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="statement",
            field=models.TextField(
                blank=True,
                help_text="Will appear as a block quote under the image.",
                verbose_name="Connection to Community Resilience Statement",
            ),
        ),
    ]
