# Generated by Django 4.2.7 on 2024-05-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_artifact_alt_text_alter_artifact_attribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Visioning the Future", verbose_name="Ready for publishing on the hub"
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="comp_community",
            field=models.BooleanField(
                default=False,
                help_text="A theme from the City of Roanoke’s 2040 Comprehensive Plan",
                verbose_name="Healthy Community",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="comp_environment",
            field=models.BooleanField(
                default=False,
                help_text="A theme from the City of Roanoke’s 2040 Comprehensive Plan",
                verbose_name="Livable Built Environment",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="comp_equity",
            field=models.BooleanField(
                default=False,
                help_text="A theme from the City of Roanoke’s 2040 Comprehensive Plan",
                verbose_name="Interwoven Equity",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="comp_nature",
            field=models.BooleanField(
                default=False,
                help_text="A theme from the City of Roanoke’s 2040 Comprehensive Plan",
                verbose_name="Harmony with Nature",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="conn_future",
            field=models.BooleanField(
                default=False,
                help_text="Connection to high school community planning program",
                verbose_name="Visioning the Future",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="conn_past",
            field=models.BooleanField(
                default=False,
                help_text="Connection to high school community planning program",
                verbose_name="Processing the Past",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="conn_present",
            field=models.BooleanField(
                default=False,
                help_text="Connection to high school community planning program",
                verbose_name="Understanding the Present",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="date",
            field=models.DateField(help_text="The date of the event/engagement/activity."),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="description",
            field=models.TextField(
                help_text="A short (2-3 sentence) explanation about what the event/engagement/activity was and its connection to heat resilience."
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="place",
            field=models.ForeignKey(
                help_text="The relevant location for the event. Must be a specific place, not a region. Make sure to add the place before filling out this form.",
                on_delete=django.db.models.deletion.PROTECT,
                to="events.place",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="title",
            field=models.CharField(help_text="A name for your event/engagement/activity.", max_length=255),
        ),
    ]
