# Generated by Django 4.2.7 on 2024-05-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_engagement_approved_alter_engagement_comp_community_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="alt_text",
            field=models.CharField(
                help_text="Caption for the image, also used as the alt text.",
                max_length=255,
                verbose_name="Image Caption",
            ),
        ),
    ]
