# Generated by Django 4.2.7 on 2024-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_alter_artifact_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubelink",
            name="attribution",
            field=models.CharField(
                blank=True,
                help_text="Will appear as the attribution for the connection to resilience statement (aka who said the statement).",
                max_length=255,
                verbose_name="Attribution for Statement",
            ),
        ),
        migrations.AddField(
            model_name="youtubelink",
            name="statement",
            field=models.TextField(
                blank=True,
                help_text="Will appear as a block quote under the image.",
                verbose_name="Connection to Community Resilience Statement",
            ),
        ),
    ]
