# Generated by Django 4.2.7 on 2024-05-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_youtubelink_attribution_youtubelink_statement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="conn_future",
            field=models.BooleanField(
                default=False,
                help_text="Does the engagement encourage reflection on the future?",
                verbose_name="Visioning the Future",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="conn_past",
            field=models.BooleanField(
                default=False,
                help_text="Does the engagement encourage reflection on the past?",
                verbose_name="Processing the Past",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="conn_present",
            field=models.BooleanField(
                default=False,
                help_text="Does the engagement encourage reflection on the present?",
                verbose_name="Understanding the Present",
            ),
        ),
    ]
