# Generated by Django 4.2.7 on 2024-07-10 14:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_downloadablefile_attribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from="title"),
        ),
    ]
