# Generated by Django 4.2.7 on 2024-07-10 14:16

from django.db import migrations


def migrate_data(apps, schema_editor):
    Engagement = apps.get_model('events', 'Engagement')
    for instance in Engagement.objects.all():
        instance.save()  # Will trigger slug update

class Migration(migrations.Migration):
    dependencies = [
        ("events", "0018_engagement_slug"),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
