# Generated by Django 4.2.7 on 2024-07-23 17:22

import autoslug.fields
from django.db import migrations


def migrate_data(apps, schema_editor):
    Engagement = apps.get_model('events', 'Engagement')
    # Resave now that unique=True is on the model even though
    # it hasn't been migrated, it will change slugs then unique
    # constraint will be added to database
    for instance in Engagement.objects.all():
        instance.save()  # Will trigger slug update


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0019_auto_20240710_1016"),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="engagement",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from="title", unique=True),
        ),
    ]
